---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name:   i want to install webserver on ubuntu nodes
    apt:
      name: apache2
      stste: present

  - name:  i want to start webserver
    service:
      neme: apache2
      state: started
